### PR TITLE
ENH: Add the Apache 2.0 `LICENSE` file.

### PR DESCRIPTION
**Pull request by jhlegarreta**
Add the Apache 2.0 `LICENSE` file.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
@SRigaud @agouaillard could you please approve or dismiss the PR? In the latter case, could you specify a license compatible with the ISC standards?

**Comment by SRigaud** [comment]
Sorry for the late answer. I don't know for @agouaillard, but I'm fine with the Apache 2.0 licence.

**Comment by agouaillard** [comment]
works for me. Approved.

**Review by dzenanz — APPROVED** [review]

**Comment by jhlegarreta** [comment]
Thanks @SRigaud and @agouaillard !

**Pull request merged**
